---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1575278/public_html/production
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH/.env
    - cd $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
